### PR TITLE
Prevent browser caching of assets

### PR DESCRIPTION
**Pull request by cylkee**
Apply a query string to the assets based on file modified time.

### CODE REVIEW

**Comment by animaux** [comment]
Good Idea in general. But I find it’s not really needed anymore once the site is up and running. Hmmmm.

**Comment by cylkee** [comment]
Thanks.

Use case: client asks for additional functionality in back-end UI which is best achieved with a change to the backend_assets's CSS and/or JS.  They can't see the change when you ask them to refresh.  Cue awkward tech support talking them through a force-refresh.

I found that iOS Safari would not always pull a fresh copy on refresh, and other browsers required a forced refresh.

I can't see any harm in adding this cache-busting functionality.  The browser should only retrieve a new copy when the file is modified on the server.

**Comment by animaux** [comment]
Convinced, here you go `;)`

**Comment by cylkee** [comment]
🥳

**Comment by cylkee** [comment]
A little background and context https://csswizardry.com/2019/03/cache-control-for-civilians/#cache-busting

**Pull request merged**
